# MCIS6273 Data Mining (Prof. Maull) / Fall 2017 / HW0 SOLUTION

**This assignment is worth up to 20 POINTS to your grade total if you complete it on time.**

| Points <br/>Possible | Due Date | Time Commitment <br/>(estimated) |
|:---------------:|:--------:|:---------------:|
| 20 | Wednesday, Sep 06 @ Midnight | 4 hours or less |


* **GRADING:** Grading will be aligned with the completeness of the objectives.

* **INDEPENDENT WORK:** Copying, cheating, plagiarism  and academic dishonesty _are not tolerated_ by Univerisity or course policy.  Please see the syllabus for the full departmental and University statement on the academic code of honor.

## OBJECTIVES
* Familiarize yourself with [Github](https://github.com)

* Work with exploring unstructured data with Python and text

* Work with a large dataset and understand data munging in Python Pandas

## WHAT TO TURN IN
You are being encouraged to turn the assignment in using the provided Jupyter Notebook.  To do so, 
clone [the course repository](https://github.com/kmsaumcis) and modify the `hw0.ipynb` file in the `homework/` 
directory.  If you do not know how to do this, please ask, or visit one of the many tutorials out there on 
the basics of using Github and cloning repositories.

Turn in a copy of a `.ipynb` file, a PDF or Word Document to Blackboard with the answers to the questions
labeled with the &#167; sign.

## ASSIGNMENT TASKS
### (0%) Familiarize yourself with [Github](https://github.com) 

[Github](http://github.com) is the _de facto_ home of open source software on 
the web.  While there are other platforms that provide similar (and in some 
cases better) services, it is still *the place* for some of the largest open 
source software projects in the world.  You will be creating an account on 
Github for several reasons:

  1. we will be using Github to store, transmit and share homework and 
  lecture notes,
  2. we will use Github for at all assignments,
  3. at some point in your future, you will _very likely_ be using Github, 
  if for private work for a company or public work on an open source project.

&#167;  **Find ONE Github repository of interest and explore it**.  There is 
**nothing to turn in** for this task -- just begin to explore Github.



### (25%) Work with exploring unstructured data with Python and text 

In this part, you will explore some text data and get a little familiar
with Python's  parsing and text capabilities.  You will grab data from
the free books provided online from [Project Gutenberg](http://gutenberg.org) 
and use the provided code to compare these documents.  Turn in the answers to 
the given tasks after studying the code provided in `gutenberg_get_words()` 
which takes a url for a book on Project Gutenberg and returns a list of the 
words in the book.  Notice the `stopwords=` parameter is used to eliminate 
words that relay low or no information.  This is a common technique use in 
text processing.

These five books will be used for the tasks for this question:

| Book                | URL                                     |
|--------------------:|----------------------------------------:|
|The Prince, Machiavelli | [http://www.gutenberg.org/cache/epub/1232/pg1232.txt](http://www.gutenberg.org/cache/epub/1232/pg1232.txt) |
|Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley|[http://www.gutenberg.org/cache/epub/84/pg84.txt](http://www.gutenberg.org/cache/epub/84/pg84.txt)|
|Siddhartha by Hermann Hesse|[http://www.gutenberg.org/cache/epub/2500/pg2500.txt](http://www.gutenberg.org/cache/epub/2500/pg2500.txt)|
|The Republic by Plato|[http://www.gutenberg.org/cache/epub/1497/pg1497.txt](http://www.gutenberg.org/cache/epub/1497/pg1497.txt)|
|The Federalist Papers by Alexander Hamilton, John Jay, and James Madison| http://www.gutenberg.org/cache/epub/1404/pg1404.txt |

&#167;  **submit the Python code that does the following:** 

- using the code and the 5 books provided above, explore and
apply the very nice Python library 
called [`collections`](https://docs.python.org/2/library/collections.html). 
Use the [`Counter`](https://docs.python.org/2/library/collections.html#collections.Counter) 
class to load the word frequencies of each book into a Python dictionary.

- **NOTE**: you will need to be online with an internet connection
for this to work, since it loads the data directly from the URLs
of the books.

In [1]:
US_STOPWORDS = ["a", "about", "above", "above", "across", "after", "afterwards", "again", "against", "all", "almost", "alone", "along", "already", "also","although","always","am","among", "amongst", "amoungst", "amount",  "an", "and", "another", "any","anyhow","anyone","anything","anyway", "anywhere", "are", "around", "as",  "at", "back","be","became", "because","become","becomes", "becoming", "been", "before", "beforehand", "behind", "being", "below", "beside", "besides", "between", "beyond", "bill", "both", "bottom","but", "by", "call", "can", "cannot", "cant", "co", "con", "could", "couldnt", "cry", "de", "describe", "detail", "do", "done", "down", "due", "during", "each", "eg", "eight", "either", "eleven","else", "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone", "everything", "everywhere", "except", "few", "fifteen", "fify", "fill", "find", "fire", "first", "five", "for", "former", "formerly", "forty", "found", "four", "from", "front", "full", "further", "get", "give", "go", "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his", "how", "however", "hundred", "ie", "if", "in", "inc", "indeed", "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter", "latterly", "least", "less", "ltd", "made", "many", "may", "me", "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly", "move", "much", "must", "my", "myself", "name", "namely", "neither", "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on", "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our", "ours", "ourselves", "out", "over", "own","part", "per", "perhaps", "please", "put", "rather", "re", "same", "see", "seem", "seemed", "seeming", "seems", "serious", "several", "she", "should", "show", "side", "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone", "something", "sometime", "sometimes", "somewhere", "still", "such", "system", "take", "ten", "than", "that", "the", "their", "them", "themselves", "then", "thence", "there", "thereafter", "thereby", "therefore", "therein", "thereupon", "these", "they", "thickv", "thin", "third", "this", "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward", "towards", "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", "via", "was", "we", "well", "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", "whoever", "whole", "whom", "whose", "why", "will", "with", "within", "without", "would", "yet", "you", "your", "yours", "yourself", "yourselves", "the"]

def gutenberg_get_words(url="http://www.gutenberg.org/cache/epub/1232/pg1232.txt", range=slice(0,None), stopwords=[]):
    import requests
    import re
    
    r = requests.get(url)
    data = re.sub(r"[^\w\s]", "", str(r.text)).lower()
   
    return \
        [w for w in data.split() if w not in stopwords]

In [2]:
booklist = \
[
    ('The Prince, Machiavelli', 'http://www.gutenberg.org/cache/epub/1232/pg1232.txt'),
    ('Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley', 'http://www.gutenberg.org/cache/epub/84/pg84.txt'),
    ('Siddhartha by Hermann Hesse', 'http://www.gutenberg.org/cache/epub/2500/pg2500.txt'),
    ('The Republic by Plato', 'http://www.gutenberg.org/cache/epub/1497/pg1497.txt'),
    ('The Federalist Papers by Alexander Hamilton, John Jay, and James Madison', 'http://www.gutenberg.org/cache/epub/1404/pg1404.txt')
]

In [3]:
from collections import Counter

word_freq_top30 = {}

for book, url in booklist:
    words = gutenberg_get_words(url, stopwords=US_STOPWORDS)
    word_freq_top30[book] = Counter(words).most_common(30)

In [4]:
word_freq_top30

{'Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley': [('i',
   2840),
  ('man', 131),
  ('did', 119),
  ('life', 114),
  ('father', 113),
  ('shall', 107),
  ('eyes', 104),
  ('said', 102),
  ('time', 98),
  ('saw', 94),
  ('project', 87),
  ('night', 87),
  ('elizabeth', 86),
  ('mind', 85),
  ('day', 80),
  ('felt', 79),
  ('work', 78),
  ('death', 76),
  ('heart', 76),
  ('feelings', 76),
  ('thought', 74),
  ('dear', 72),
  ('soon', 71),
  ('friend', 70),
  ('passed', 67),
  ('miserable', 65),
  ('heard', 62),
  ('like', 61),
  ('place', 60),
  ('love', 59)],
 'Siddhartha by Hermann Hesse': [('i', 395),
  ('siddhartha', 379),
  ('govinda', 139),
  ('time', 139),
  ('like', 138),
  ('river', 108),
  ('saw', 99),
  ('long', 97),
  ('said', 95),
  ('did', 88),
  ('life', 88),
  ('project', 87),
  ('man', 84),
  ('thought', 82),
  ('love', 80),
  ('learned', 80),
  ('teachings', 77),
  ('just', 74),
  ('felt', 74),
  ('people', 74),
  ('kamala', 72),
  ('heart', 71),
  ('world', 68),
  ('face', 67),
  ('eyes', 66),
  ('oh', 66),
  ('friend', 65),
  ('know', 63),
  ('samana', 62),
  ('spoke', 61)],
 'The Federalist Papers by Alexander Hamilton, John Jay, and James Madison': [('states',
   863),
  ('government', 827),
  ('state', 792),
  ('power', 619),
  ('people', 614),
  ('constitution', 466),
  ('i', 382),
  ('union', 375),
  ('new', 370),
  ('national', 342),
  ('federal', 326),
  ('authority', 295),
  ('public', 294),
  ('great', 294),
  ('ought', 275),
  ('general', 270),
  ('powers', 266),
  ('shall', 257),
  ('executive', 257),
  ('united', 248),
  ('time', 248),
  ('men', 236),
  ('members', 230),
  ('number', 229),
  ('body', 225),
  ('particular', 221),
  ('different', 214),
  ('subject', 213),
  ('laws', 210),
  ('legislative', 210)],
 'The Prince, Machiavelli': [('prince', 222),
  ('i', 216),
  ('men', 161),
  ('castruccio', 136),
  ('people', 115),
  ('having', 109),
  ('ought', 94),
  ('time', 93),
  ('great', 89),
  ('duke', 88),
  ('project', 87),
  ('state', 85),
  ('did', 81),
  ('man', 79),
  ('new', 75),
  ('make', 73),
  ('good', 71),
  ('king', 69),
  ('arms', 63),
  ('fortune', 62),
  ('work', 62),
  ('way', 61),
  ('florentines', 61),
  ('necessary', 60),
  ('princes', 59),
  ('italy', 58),
  ('fear', 57),
  ('things', 57),
  ('gutenbergtm', 56),
  ('said', 55)],
 'The Republic by Plato': [('i', 1782),
  ('said', 1117),
  ('state', 684),
  ('good', 657),
  ('man', 599),
  ('true', 585),
  ('like', 477),
  ('yes', 466),
  ('men', 426),
  ('say', 420),
  ('life', 390),
  ('justice', 358),
  ('soul', 338),
  ('nature', 336),
  ('plato', 325),
  ('just', 309),
  ('knowledge', 292),
  ('replied', 271),
  ('let', 264),
  ('shall', 264),
  ('truth', 263),
  ('certainly', 260),
  ('great', 260),
  ('things', 243),
  ('world', 241),
  ('way', 235),
  ('mind', 230),
  ('evil', 226),
  ('make', 224),
  ('time', 214)]}

In [5]:
for k, v in word_freq_top30.items():
    v = [word for word, count in v]
    for j, v_ in word_freq_top30.items():
        v_ = [word for word, count in v_]
        if j != k:
            common_words = set(v).intersection(set(v_))
            print("{} <=> {}\n\t{} common words: {}".format(k, j, len(common_words), common_words))
    print("\n\n")

The Prince, Machiavelli <=> Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley
	7 common words: {'time', 'work', 'project', 'did', 'said', 'man', 'i'}
The Prince, Machiavelli <=> Siddhartha by Hermann Hesse
	7 common words: {'project', 'people', 'did', 'i', 'said', 'man', 'time'}
The Prince, Machiavelli <=> The Republic by Plato
	11 common words: {'things', 'great', 'men', 'good', 'make', 'i', 'said', 'state', 'way', 'man', 'time'}
The Prince, Machiavelli <=> The Federalist Papers by Alexander Hamilton, John Jay, and James Madison
	8 common words: {'time', 'great', 'men', 'people', 'new', 'state', 'i', 'ought'}



Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley <=> The Prince, Machiavelli
	7 common words: {'time', 'work', 'project', 'did', 'said', 'man', 'i'}
Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley <=> Siddhartha by Hermann Hesse
	15 common words: {'friend', 'like', 'saw', 'project', 'felt', 'did', 'i', 'said', 'thought', 'love', 'heart', 'man', 'time', 'eyes', 'life'}
Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley <=> The Republic by Plato
	8 common words: {'life', 'like', 'i', 'said', 'man', 'shall', 'time', 'mind'}
Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley <=> The Federalist Papers by Alexander Hamilton, John Jay, and James Madison
	3 common words: {'time', 'shall', 'i'}



Siddhartha by Hermann Hesse <=> The Prince, Machiavelli
	7 common words: {'time', 'project', 'people', 'did', 'said', 'man', 'i'}
Siddhartha by Hermann Hesse <=> Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley
	15 common words: {'friend', 'time', 'like', 'saw', 'project', 'felt', 'did', 'said', 'thought', 'love', 'heart', 'man', 'i', 'eyes', 'life'}
Siddhartha by Hermann Hesse <=> The Republic by Plato
	8 common words: {'like', 'just', 'i', 'said', 'man', 'time', 'world', 'life'}
Siddhartha by Hermann Hesse <=> The Federalist Papers by Alexander Hamilton, John Jay, and James Madison
	3 common words: {'time', 'people', 'i'}



The Republic by Plato <=> The Prince, Machiavelli
	11 common words: {'things', 'time', 'great', 'men', 'good', 'make', 'said', 'state', 'way', 'man', 'i'}
The Republic by Plato <=> Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley
	8 common words: {'time', 'like', 'said', 'mind', 'man', 'shall', 'i', 'life'}
The Republic by Plato <=> Siddhartha by Hermann Hesse
	8 common words: {'like', 'just', 'i', 'said', 'man', 'time', 'world', 'life'}
The Republic by Plato <=> The Federalist Papers by Alexander Hamilton, John Jay, and James Madison
	6 common words: {'time', 'great', 'men', 'state', 'shall', 'i'}



The Federalist Papers by Alexander Hamilton, John Jay, and James Madison <=> The Prince, Machiavelli
	8 common words: {'time', 'great', 'men', 'people', 'new', 'state', 'i', 'ought'}
The Federalist Papers by Alexander Hamilton, John Jay, and James Madison <=> Frankenstein; Or, The Modern Prometheus by Mary Wollstonecraft Shelley
	3 common words: {'time', 'shall', 'i'}
The Federalist Papers by Alexander Hamilton, John Jay, and James Madison <=> Siddhartha by Hermann Hesse
	3 common words: {'people', 'time', 'i'}
The Federalist Papers by Alexander Hamilton, John Jay, and James Madison <=> The Republic by Plato
	6 common words: {'great', 'men', 'i', 'state', 'shall', 'time'}

&#167;  **turn in _at least_ 2 sentences and any code if you used code 
to answering the following:** 

- there are similarities and differences 
in the top 30 words of the five provided documents -- be specific about
describing what they are?  How similar 
or different are each of the top 30 words list?
You can compare them by hand (look at them) or you are encouraged to
write Python code to compare them automatically.

### (75%) Work with a large dataset and understand data munging in Python Pandas 

As we have learned in class, a great deal of time doing data mining involves understanding 
the data in a dataset and preprocessing it in preparation for working with it in a real 
analysis of some sort.  We will develop an understanding of:

  * importing CSV data into Pandas DataFrames,
  * exporting JSON data from a Pandas DataFrame,
  * understand how to compute data from DataFrame elements
  
You might find the [Pandas IO](http://pandas.pydata.org/pandas-docs/stable/io.html) library 
helpful in completing this task.

We will be using an interesting data source: **US Baseball Statistics Archive** by 
Sean Lahman (CCBY-SA 3.0), which can be found in these two locations.  You can download the
entire archive to your local machine.

  * [http://seanlahman.com/baseball-archive/statistics/](http://seanlahman.com/baseball-archive/statistics/)
  * [https://github.com/chadwickbureau/baseballdatabank](https://github.com/chadwickbureau/baseballdatabank)

&#167;  **submit the code to load the batting table** from the Baseball Archive directly from the 
Github repository into a Pandas DataFrame.  

- You can use the CSV file at 
[this url](https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Batting.csv).
You will most certainly be using the [`read_csv()` method](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html).

In [7]:
import pandas as pd
df = pd.read_csv('./data/Batting.csv') # reading locally

&#167;  **submit the code to write the JSON file that contains all the batting records for the Cincinnati 
Reds (CIN) in 1981**.  
            
- This will require a simple query into the dataset (loaded as a DataFrame) -- please read the [documentation 
on boolean indexing](http://pandas.pydata.org/pandas-docs/stable/indexing.html#boolean-indexing).

- You will need to explore the [`to_json()`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_json.html#pandas.DataFrame.to_json) method to then convert the DataFrame that results from the query above into a JSON object.

In [8]:
df.head()

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,abercda01,1871,1,TRO,NaN,1,4,0,0,0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
1,addybo01,1871,1,RC1,NaN,25,118,30,32,6,...,13.0,8.0,1.0,4,0.0,NaN,NaN,NaN,NaN,NaN
2,allisar01,1871,1,CL1,NaN,29,137,28,40,4,...,19.0,3.0,1.0,2,5.0,NaN,NaN,NaN,NaN,NaN
3,allisdo01,1871,1,WS3,NaN,27,133,28,44,10,...,27.0,1.0,1.0,0,2.0,NaN,NaN,NaN,NaN,NaN
4,ansonca01,1871,1,RC1,NaN,25,120,29,39,11,...,16.0,6.0,2.0,2,1.0,NaN,NaN,NaN,NaN,NaN

In [9]:
df_cinc81 = df[(df.teamID=='CIN') & (df.yearID==1981)]
df_cinc81.to_json('cinc81_batting.json')

&#167;  **submit the code that calculates the following batting rank score for the 1981 Reds (CIN)** 
$$ \varphi =\ G {H \over AB} +  {{RBI} \over \sqrt {R}} $$
**where $G, H, AB, RBI, R$ are _games_, _hits_, _at bats_, _runs batted in_ and _runs_ respectively.**

- Your answer should ONLY include the batting for the **1981 Cincinnati Reds batting roster**.

In [10]:
# while not a requirement for the assignment, we should take out problematic 0 values (in a denomenator) to make out output cleaner
df_cinc81 = df_cinc81[(df_cinc81.AB>0) & (df_cinc81.R>0)]

In [11]:
df_cinc81['score_varphi'] = df_cinc81.G * ( df_cinc81.H /  df_cinc81.AB) +  df_cinc81.RBI / (df_cinc81.R**.5)

In [12]:
df_cinc81.head()

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,score_varphi
58351,bairdo01,1981,1,CIN,NL,24,3,1,1,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,11.000000
58363,barrage01,1981,1,CIN,NL,9,6,2,2,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,3.707107
58375,benchjo01,1981,1,CIN,NL,52,178,14,55,8,...,0.0,2.0,17,21.0,3.0,0.0,1.0,0.0,4.0,22.748947
58378,berenbr01,1981,1,CIN,NL,21,42,4,8,3,...,0.0,0.0,2,18.0,0.0,0.0,3.0,1.0,1.0,4.500000
58388,biittla01,1981,1,CIN,NL,42,61,1,13,4,...,0.0,0.0,4,4.0,1.0,0.0,0.0,1.0,3.0,16.950820

&#167;  **for the 1981 data submit the top 4 batter IDs by their batting rank score, $\varphi$, previously calculated.**

In [13]:
df_cinc81[['playerID', 'score_varphi']].sort_values(by='score_varphi', ascending=False).head(4)

        playerID  score_varphi
58577  fostege01     43.076087
58477  conceda01     41.354177
58618  griffke01     35.588393
58931  oestero01     34.735567